function splatterMel_AttentionTask(ppsRawDataDir, analysisDir)

fprintf('> Running %s\n', mfilename);

theFolders = {'MaxLMS400pct/HERO_asb1/040716/MatFiles' ...
    'MaxLMS400pct/HERO_aso1/033016/MatFiles' ...
    'MaxLMS400pct/HERO_gka1/040116/MatFiles' ...
    'MaxLMS400pct/HERO_mxs1/040816/MatFiles' ...
    'MaxLMSCRF/HERO_asb1/060816/MatFiles' ...
    'MaxLMSCRF/HERO_aso1/060116/MatFiles' ...
    'MaxLMSCRF/HERO_gka1/060616/MatFiles' ...
    'MaxLMSCRF/HERO_mxs1/061016/MatFiles' ...
    'MaxLMSCRF/HERO_mxs1/062416/MatFiles' ...
    'MaxLMSCRF/HERO_mxs1/062816/MatFiles' ...
    'MaxMel400pct/HERO_asb1/032416/MatFiles' ...
    'MaxMel400pct/HERO_aso1/032516/MatFiles' ...
    'MaxMel400pct/HERO_gka1/031516/MatFiles' ...
    'MaxMel400pct/HERO_gka1/033116/MatFiles' ...
    'MaxMel400pct/HERO_gka1/052616/MatFiles' ...
    'MaxMel400pct/HERO_mxs1/040616/MatFiles' ...
    'MaxMelCRF/HERO_asb1/052716/MatFiles' ...
    'MaxMelCRF/HERO_asb1/060716/MatFiles' ...
    'MaxMelCRF/HERO_aso1/053116/MatFiles' ...
    'MaxMelCRF/HERO_gka1/060216/MatFiles' ...
    'MaxMelCRF/HERO_mxs1/060916/MatFiles' ...
    'MaxMelCRF/HERO_mxs1/061016/MatFiles' ...
    'RodControl/HERO_asb1/101916/MatFiles' ...
    'RodControl/HERO_gka1/101916/MatFiles' ...
    'RodControl/HERO_gka1/102416/MatFiles' ...
    'RodControl/HERO_mxs1/101916/MatFiles' ...
    'RodControl/HERO_mxs1/102416/MatFiles' ...
    'SplatterControlCRF/HERO_asb1/051016/MatFiles' ...
    'SplatterControlCRF/HERO_aso1/042916/MatFiles' ...
    'SplatterControlCRF/HERO_gka1/050616/MatFiles' ...
    'SplatterControlCRF/HERO_mxs1/050916/MatFiles'};
outTable = fullfile(analysisDir, 'tables/Table_AttentionTaskPerformance.csv');

fid = fopen(outTable, 'w');
fprintf(fid, 'Protocol,Subject,Date,HR,FA\n');

for f1 = 1:length(theFolders)
    % Which .mat files do we have?
    theMATFiles = dir(fullfile(ppsRawDataDir, theFolders{f1}, '/*.mat'));
    
    tmp0 = strsplit(fullfile(ppsRawDataDir, theFolders{f1}), '/');
    theDate = tmp0{end-1};
    theSub = tmp0{end-2};
    theProtocol = tmp0{end-3};
    
    sumFA = 0;
    sumHR = 0;
    sumTask = 0;
    sumNotTask = 0;
    
    for f2 = 1:length(theMATFiles)
        tmp = load(fullfile(ppsRawDataDir, theFolders{f1}, theMATFiles(f2).name));
        
        if isfield(tmp.params, 'responseStruct')
            theResponseStruct = tmp.params.responseStruct;
        else
            tmp.responseStruct;
        end
        
        theAttentionTask = zeros(1, length(theResponseStruct.events));
        theConditions = strsplit(tmp.params.modulationFiles, ',');
        for ii = 1:length(theConditions)
            if ~isempty(strfind(theConditions{ii}, 'Attention'))
                attnTaskIdx = ii;
            end
        end
        theAttentionTask = (tmp.params.theDirections == ii);
        
        theResp = zeros(1, length(theResponseStruct.events));
        for ii = 1:length(theResponseStruct.events)
            if ~isempty(theResponseStruct.events(ii).buffer)
                if ~isempty(find([theResponseStruct.events(ii).buffer.keyCode] ~= 18))
                    theResp(ii) = 1;
                end
            end
        end
        % Calculate HR and FA
        sumFA = sumFA + sum(theResp & ~theAttentionTask);
        sumNotTask = sumNotTask + sum(~theAttentionTask);
        sumHR = sumHR + sum(theResp & theAttentionTask);
        sumTask = sumTask + sum(theAttentionTask);
    end
    fprintf(fid, '%s,%s,%s,%.3f,%.3f\n', theProtocol, theSub, theDate, sumHR/sumTask, sumFA/sumNotTask);
end

fclose(fid);